# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest' if your project needs Windows

steps:
- task: NodeTool@0 # Corrected task name and version
  inputs:
    versionSpec: '10.x' # The flatris project appears to be older, so an older Node.js might be more compatible. You might need to experiment with 12.x or 14.x if 10.x causes other issues.
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'