# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' # Use 'ubuntu-latest' for Linux agent

steps:
- task: NodeTool@0 # Using NodeTool@0 is often preferred and more generic.
  inputs:
    versionSpec: '10.x' # Or '12.x', '14.x', '16.x' - experiment if 10.x causes issues.
  displayName: 'Install Node.js'

- script: | # This is a multi-line script, so the | is important.
    npm install --legacy-peer-deps
  displayName: 'npm install'

- script: | # This is also a script block.
    touch .env
  displayName: 'Create .env file'

- script: | # Another script block.
    npm run build
  displayName: 'npm build'